server:
  port: 9001


spring:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql

  ## 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/practice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true
    username: root
    password: 123456

    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial: 2
      min-idle: 1
      max-active: 2

  ## redis配置
redis:
  host: 127.0.0.1
  database: 8
  port: 6379
  # password: admin



# mybatis配置
mybatis:
  type-aliases-package: com.draymond.my_boot.entity
  mapper-locations: classpath*:mapper/generalMap/*.xml

  #------------------------ 线程池配置 ------------------------
  #IO密集型应用，线程数为2N+1
thread-pool-factory:
  corePoolSize: 100
  maxPoolSize:  200
  queueCapacity: 150
  keepAliveSeconds: 120


